language: php

php:
  - 7.2

addons:
  ssh_known_hosts: targygraf.hu

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-suggest

script: vendor/bin/phpunit

before_deploy:
  - openssl aes-256-cbc -K $encrypted_1e75d07664e9_key -iv $encrypted_1e75d07664e9_iv -in .deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: bash .travis_deploy.sh
  on:
    branch: master
