language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-suggest

script: vendor/bin/phpunit

deploy:
  provider: script
  script: ./.travis-deploy.sh
  on:
    branch: master
