name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer config --no-plugins allow-plugins.kylekatarnls/update-helper false
      - run: composer install --profile --no-interaction
      - run: ./vendor/bin/phpunit
